// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLYTzBNna0rv_7LzOg4Yo5FmiEe4sPzBo',
    appId: '1:477534044858:android:f9b5921d658d0c3caeb883',
    messagingSenderId: '477534044858',
    projectId: 'course-motobike-3d695',
    storageBucket: 'course-motobike-3d695.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3-GU3qFV39ZPGQF_pnBzPjFu7kjb-49M',
    appId: '1:477534044858:ios:fd65634931e1bc75aeb883',
    messagingSenderId: '477534044858',
    projectId: 'course-motobike-3d695',
    storageBucket: 'course-motobike-3d695.appspot.com',
    iosBundleId: 'com.example.flutterMotobikeCsApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDJ3vaRth6ziL2vuYapdyNS_AdpofqjW4Q',
    appId: '1:477534044858:web:64fe873a1ae923d2aeb883',
    messagingSenderId: '477534044858',
    projectId: 'course-motobike-3d695',
    authDomain: 'course-motobike-3d695.firebaseapp.com',
    storageBucket: 'course-motobike-3d695.appspot.com',
    measurementId: 'G-DS78EDFMYJ',
  );

}